import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = os.path.join(BASE_DIR, "logs")
MODEL_DIR = os.path.join(BASE_DIR, "models")

TEST_MODE = False
GEN_SIZE = 32
MATCH_DURATION = 20

NUM_PROCESSES = 6
MAX_VISIBLE_WINDOWS = 0
HEADLESS = True

WINDOW_WIDTH = 300
AUTO_LAYOUT = True
AGENTS_PER_WINDOW = 0

VISION_RES = 12
HIDDEN_LAYER_SIZE = 64

GRAVITY = 40
JUMP_FORCE = 15
BASE_SPEED = 10
BHOP_SPEED_BOOST = 2.0
STRAFE_PENALTY = 0.6
BHOP_WINDOW = 0.15

MUTATION_RATE_START = 0.2
MUTATION_RATE_END = 0.02
MUTATION_DECAY_SPEED = 0.0001
SCORE_TO_INCREASE_DIFFICULTY = 500
STAGNATION_LIMIT = 20
EXTINCTION_LIMIT = 50

LOAD_SAVE = True
LOAD_FILE = "testing_model.pkl"
SAVE_FILE = "testing_model.pkl"
BACKUP_INTERVAL = 5
ANTI_SPIN_THRESHOLD = 0.1
MAX_BAD_GENS = 3
LOG_FILE = "testing_log.txt"
ERROR_LOG_FILE = "testing_errors.txt"

STARTING_WALLS = 40
MAX_WALLS = 70
