import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = os.path.join(BASE_DIR, "logs")
MODEL_DIR = os.path.join(BASE_DIR, "models")

TEST_MODE = False
GEN_SIZE = 1
MATCH_DURATION = 15

NUM_PROCESSES = 1
MAX_VISIBLE_WINDOWS = 1
HEADLESS = False

FULLSCREEN = False
WINDOW_WIDTH = 800
AUTO_LAYOUT = False
AGENTS_PER_WINDOW = 1

HIDDEN_LAYER_SIZE = 64
INPUT_SIZE = 14
OUTPUT_SIZE = 4

GRAVITY = 40
JUMP_FORCE = 15
BASE_SPEED = 10
BHOP_SPEED_BOOST = 2.0
STRAFE_PENALTY = 0.6
BHOP_WINDOW = 0.15

LEARNING_RATE = 0.001
GAMMA = 0.99

SCORE_TO_INCREASE_DIFFICULTY = 500
STAGNATION_LIMIT = 20
EXTINCTION_LIMIT = 50

LOAD_SAVE = False
LOAD_FILE = "testing_model.pth"
SAVE_FILE = "testing_model.pth"
BACKUP_INTERVAL = 5
MAX_BAD_GENS = 3
LOG_FILE = "testing_log.txt"
ERROR_LOG_FILE = "testing_errors.txt"

STARTING_WALLS = 40
MAX_WALLS = 70